### ISSUE TITLE
Missing the last attribute

### ISSUE THREAD

**Issue by amitbha** [coderobe/hq#2]
`echo '<a t1="1" t2="2"></a>' | hq a attr t2`
**no output.**

`echo '<a t1="1" t2="2"></a>' | hq a attr t1`
output: 1

Seems hq omit the last attribute.

| name | info
|------------ | -------------
| version: | hq 3.0
| os: | Manjaro 18.0.4 Illyria

**Comment by coderobe** [comment]
Thanks for reporting! Fixed with https://github.com/coderobe/hq/commit/33a666aaa55771b75f7000cca0c84431fd354cf5
