### ISSUE TITLE
Infinite loop when using []

### ISSUE THREAD

**Issue by Dialga** [coderobe/hq#3]
Hi,
If I run `hq 'html body div[2]' text` hq gets stuck and there is no output, where I'm expecting to get the second div's text.

**Comment by coderobe** [comment]
That's not a valid CSS Selector. The `[]` operator selects on element attributes - e.g. `input[type=text]` would match `<input type="text" />` but not `<input type="password" />`. The way you're using it as if it was an array accessor is invalid.

Though it shouldn't get stuck either, it should simply not return any matches - ever. Element attributes cannot start with a number (i.e. `<div 2></div>` is invalid). I'll look into this behavior.

Meanwhile, please take a look at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors to learn how to properly format your selector query. You probably want `:nth-of-type`, or maybe even just `:nth`.

**Comment by coderobe** [comment]
I can reproduce the hang when passing an invalid attribute selector. I will examine that when i get the time.

**Comment by Dialga** [comment]
I used the XPath from chrome's dev tools, so I guess hq doesn't support xpaths?

**Comment by coderobe** [comment]
XPath is XSLT, not Selectors. hq exclusively supports selector matching

**Comment by coderobe** [comment]
FWIW, the chrome devtools also allow to `Copy selector` in the same menu you got the XPath from. That is the correct one to use.
