### ISSUE TITLE
Missing the last attribute, again

### ISSUE THREAD

**Issue by Smackd0wn** [coderobe/hq#7]
Perhaps related to #2, on hq version 3.1:

`echo '<a t1="1"></a><a t1=""></a><a t1="2"></a><a t1="3"></a>' | hq a attr t1`

output:
```
1



```

expected:

```
1

2
3
```

**Comment by coderobe** [comment]
Possibly fixed with https://github.com/coderobe/hq/commit/3fe3780727ee34241ede5acc3056e1fea05c0108

**Comment by coderobe** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8442384/233172869-f961b3ba-b004-4de5-874d-fc2f6e56c6ec.png">

seems to work
